# Generated by Django 4.2.27 on 2026-01-10 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('source', models.CharField(choices=[('contact', 'Kontakt forma'), ('registration', 'Registracija')], max_length=50, verbose_name='Izvor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
            ],
            options={
                'verbose_name': 'Email korisnika',
                'verbose_name_plural': 'Emailovi korisnika',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CkeditorUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, unique=True, verbose_name='Putanja fajla')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadovano')),
                ('is_used', models.BooleanField(default=False, verbose_name='Korišćeno')),
                ('used_in_model', models.CharField(blank=True, max_length=100, verbose_name='Korišćeno u')),
                ('used_in_id', models.IntegerField(blank=True, null=True, verbose_name='ID instance')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CKEditor upload',
                'verbose_name_plural': 'CKEditor uploadi',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['is_used', 'uploaded_at'], name='core_ckedit_is_used_0a790a_idx')],
            },
        ),
    ]
