# Generated by Django 4.2.27 on 2025-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('source', models.CharField(choices=[('contact', 'Kontakt forma'), ('registration', 'Registracija')], max_length=50, verbose_name='Izvor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
            ],
            options={
                'verbose_name': 'Email korisnika',
                'verbose_name_plural': 'Emailovi korisnika',
                'ordering': ['-created_at'],
            },
        ),
    ]
