# Generated by Django 4.2.27 on 2026-01-10 00:09

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta naslov')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta opis')),
                ('thumbnail', models.ImageField(upload_to=core.utils.unique_topic_thumbnail, verbose_name='Thumbnail')),
                ('short_description', models.TextField(default='', max_length=500, verbose_name='Kratak opis')),
                ('full_description', models.TextField(default='', verbose_name='Pun opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-created_at'],
            },
        ),
    ]
