# Generated by Django 4.2.27 on 2026-01-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_category_topic_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Koristi se za sortiranje kategorija u padajućem meniju', verbose_name='Redosled'),
        ),
    ]
