# Generated by Django 4.2.27 on 2026-01-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr_cyrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Naziv (ћирилица)'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_sr_cyrl',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug (ћирилица)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='full_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Full description (English)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='full_description_sr_cyrl',
            field=models.TextField(blank=True, default='', verbose_name='Pun opis (ћирилица)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description (English)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='meta_description_sr_cyrl',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta opis (ћирилица)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta title (English)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='meta_title_sr_cyrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta naslov (ћирилица)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='short_description_en',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Short description (English)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='short_description_sr_cyrl',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Kratak opis (ћирилица)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug (English)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_sr_cyrl',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug (ћирилица)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_sr_cyrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Naslov (ћирилица)'),
        ),
    ]
