# Generated by Django 4.2.27 on 2025-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta naslov')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta opis')),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnails/', verbose_name='Thumbnail')),
                ('content', models.TextField(verbose_name='Sadržaj')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Izvadak')),
                ('is_published', models.BooleanField(default=False, verbose_name='Objavljeno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog postovi',
                'ordering': ['-created_at'],
            },
        ),
    ]
