# Generated by Django 4.2.27 on 2025-12-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='full_description',
            field=models.TextField(default='', verbose_name='Pun opis'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(default='', max_length=500, verbose_name='Kratak opis'),
        ),
    ]
