# Generated by Django 4.2.27 on 2026-01-04 19:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_content_remove_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(upload_to=core.utils.unique_blog_thumbnail, verbose_name='Thumbnail'),
        ),
    ]
