# Generated by Django 4.2.27 on 2025-12-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Naziv')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Meta naslov')),
                ('meta_description', models.TextField(max_length=300, verbose_name='Meta opis')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('title', models.CharField(max_length=200, verbose_name='Naziv')),
                ('short_description', models.TextField(max_length=500, verbose_name='Kratak opis')),
                ('full_description', models.TextField(verbose_name='Pun opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena na popustu')),
                ('stock_type', models.CharField(choices=[('always', 'Uvek na stanju'), ('limited', 'Ograničena količina')], default='always', max_length=10, verbose_name='Tip zaliha')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Količina na stanju')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Proizvod',
                'verbose_name_plural': 'Proizvodi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Naziv atributa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
            ],
            options={
                'verbose_name': 'Atribut proizvoda',
                'verbose_name_plural': 'Atributi proizvoda',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Slika')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alternativni tekst')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Slika proizvoda',
                'verbose_name_plural': 'Slike proizvoda',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Vrednost')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='shop.product')),
            ],
            options={
                'verbose_name': 'Vrednost atributa',
                'verbose_name_plural': 'Vrednosti atributa',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
