# Generated by Django 4.2.27 on 2025-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_category_remove_productdimension_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ostavite prazno za "Na upit"', max_digits=10, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='productdimension',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dubina (cm)'),
        ),
    ]
