# Generated by Django 4.2.27 on 2026-01-04 19:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_price_alter_productdimension_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.unique_product_thumbnail, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.unique_product_image, verbose_name='Slika'),
        ),
    ]
