# Generated by Django 4.2.27 on 2026-01-04 19:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_thumbnail_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpattern',
            name='image',
            field=models.ImageField(upload_to=core.utils.unique_product_pattern, verbose_name='Slika dezena'),
        ),
    ]
